apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  ports:
    - port: 8000
      targetPort: 8080
      protocol: TCP
  selector:
    app: hello-world-java
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-java
spec:
  selector:
    matchLabels:
      app: hello-world-java
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world-java
    spec:
      containers:
      - name: hello-world-java
        image: bschmitt769/spring-boot-newrelic:with-agent
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512M"
            cpu: "250m"
        ports:
        - containerPort: 8080
        env:
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: nrlicensekey
              key: nrlicensekey
        - name: NEW_RELIC_APP_NAME
          value: "hello-world-java"
        - name: NEW_RELIC_LOG_FILE_NAME
          value: "STDOUT"
